### ISSUE TITLE
Icons in themes broken

### ISSUE THREAD

**Issue by keunes** [klaussinani/ao#113]
**Describe the bug**
Probably because Mycrosoft doesn't use transparent icons, but the icons in the app have a different background colour than the theme background colours. Not sure if this can be corrected on Ao's side, or if a request should be made over at Microsoft's Uservoice.

**Expected behavior**
Background of icons in dark themes have same background as rest of the screen.

**Screenshots**
![Screenshot from 2019-10-14 23-40-53](https://user-images.githubusercontent.com/11229646/66784972-33c0cd00-eedc-11e9-81e6-dc8472b60d65.png)
(with the black theme)

**Comment by akshayvinchurkar** [comment]
I just fixed the issue in the PR #114 its just a background color for icons i removed that ✌

**Comment by pythonInRelay** [comment]
Has this been added in a future update? It's still present in the latest version for me on Debian using the Dark theme.
